#!/usr/bin/env python3

import sys

from plugins.calculate import calculate
from plugins.echo import echo
from plugins.filesystem import files


def search(query):
    plugins = [files, calculate, echo]
    results = []
    for p in plugins:
        results.extend(p(query))
    return results


def i_am_feeling_lucky(query):
    r = search(query)[0]
    r.run()
    return r


if __name__ == "__main__":
    query = ' '.join(sys.argv[1:])
    [print(r) for r in search(query)]
